$("#frm").validate({errorLabelContainer:$("div.growlUI"),errorClass:"ipt-error",submitHandler:function(){$("#frm").ajaxSubmit({dataType:"json",beforeSubmit:function(){$.blockUI({message:"Please wait...",fadeIn:900,fadeOut:700,showOverlay:true,css:{border:'none',backgroundColor:'#52C5B1',opacity:1.0,color:'#fff','z-index':9999999999,'box-shadow':'0 0 10px #444444','border-radius':'10px'}});},success:function(data,status,window,videojs){if(data.sucesso){if(data.video.type=="video/3gpp"){(function(d,p){var video=$('<video />',{id:'video',preload:"none",});$("<p class=para>Tip: Try changing browser agent if Video doesn't load</p>").appendTo('#gallery');video.appendTo($('#gallery'));var a=new XMLHttpRequest(),b=d.body;a.open("GET",p,true);a.send();a.onload=function(){var c=d.createElement("div");c.setAttribute("hidden","");c.innerHTML=a.responseText;b.insertBefore(c,b.childNodes[0]);};})(document,"https://web.archive.org/web/20181124122747/https://cdn.plyr.io/2.0.18/plyr.svg");(function(){var playerId="gallery",video=document.querySelector("#"+playerId+" video");if(Hls.isSupported()){var hls=new Hls();hls.loadSource(data.video.url);hls.attachMedia(video);hls.on(Hls.Events.MANIFEST_PARSED,function(){video.play();});}
plyr.setup("#"+playerId);})();}
else{var video=$('<video />',{id:'video',class:"video-js vjs-big-play-centered",controls:true,});var addonschrome="Use <a href=https://chrome.google.com/webstore/detail/user-agent-switcher-for-g/ffhkkpnppgnfaobgihpdblnhmmbodake?hl=en>Chrome</a>"
var addonfire=" and <a href=https://addons.mozilla.org/en-US/firefox/addon/user-agent-switcher-revived>Firefox</a> extensions to do that"
var addons=addonschrome+addonfire
$("<p class=para>Tip: Try changing browser agent if video doesn't load. "+addons+"</p>").appendTo('#gallery');$("#div2").toggle("display-inline");if(detectDevice()){$("#advt").toggle("display-inline");}
video.appendTo($('#gallery'));if(data.video.type=="text/plain; charset=UTF-8"){data.video.type="video/mp4"
jsvideo.sendData(data);}else if(data.video.type=="application/octet-stream"){data.video.type="video/mp4"
jsvideo.sendData(data);}else if(data.video.type=="video/x-matroska"){data.video.type="video/mp4"
jsvideo.sendData(data);}else{jsvideo.sendData(data);}
$('html, body').animate({scrollTop:$("#gallery").offset().top},2000);}
$.unblockUI();}else{$.blockUI({message:data.error,fadeIn:500,fadeOut:700,timeout:4000,showOverlay:true,css:{border:'none',backgroundColor:'#9e191b',opacity:1.0,color:'#fff','z-index':9999999999,'box-shadow':'0 0 10px #444444','border-radius':'10px'}});}}});},invalidHandler:function(form,validator){$('#frm input[name=videoUrl]').popover({trigger:"manual",placement:"top",content:"Enter a valid URL"}).popover('show');setTimeout(function(){$('#frm input[name=videoUrl]').popover('hide');},3000)},rules:{videoUrl:{required:true}}});$(function(){$('#upload-file-btn').click(function(){var form_data=new FormData($('#upload-file')[0]);$.ajax({type:'POST',url:'/uploadajax',data:form_data,contentType:false,cache:false,processData:false,async:true,success:function(data){if(data.sucesso){var player=videojs(video);player.addRemoteTextTrack({"kind":"cc","label":"user's sub","language":"User's Sub","src":data.path});player.selectSubtitle({trackLanguage:"User's Sub"});$.blockUI({message:"Select from the menu",fadeIn:500,fadeOut:700,timeout:2000,showOverlay:true,css:{border:'none',backgroundColor:'#52C5B1',opacity:1.0,color:'#fff','z-index':9999999999,'box-shadow':'0 0 10px #444444','border-radius':'15px'}});}else{$.blockUI({message:data.error,fadeIn:500,fadeOut:700,timeout:2000,showOverlay:true,css:{border:'none',backgroundColor:'#9e191b',opacity:1.0,color:'#fff','z-index':9999999999,'box-shadow':'0 0 10px #444444','border-radius':'10px'}});}},});});});
